// This file is part of YW project. Copyright 2025 Oh Inseo (YJK)
// SPDX-License-Identifier: BSD-3-Clause
// See LICENSE for details, and LICENSE.thirdparty.md for third-party license information.

// Package css provides support for various CSS standards.
//
// # Relationship with sub-packages
//
// This package never references any of sub-packages, but sub-packages can
// freely import this package.
//
// # Code generation, and adding new CSS properties
//
// Code for most CSS properties are auto-generated by csssyntax/gen and props/gen,
// to both make it easier to add new properties, and to avoid human errors.
//
// Properties are declared in internal/propsdef, and once a new property
// has been added, "go genergate" must be called on both csssyntax and props package.
package css
