// Package css provides support for various CSS standards.
//
// # Code generation, and adding new CSS properties
//
// Code for most CSS properties are auto-generated by csssyntax/gen and props/gen,
// to both make it easier to add new properties, and to avoid human errors.
//
// Properties are declared in internal/propsdef, and once a new property
// has been added, "go genergate" must be called on both csssyntax and props package.
package css
