// Auto-generated by css_props_gen
// DO NOT EDIT.
package libhtml

import (
	"errors"
	"fmt"
)

type css_border_color_shorthand struct {
	top    css_color
	right  css_color
	bottom css_color
	left   css_color
}

func (ts *css_token_stream) parse_css_border_color_shorthand() (css_border_color_shorthand, bool) {
	items, _ := css_accept_repetion(ts, 4, func(ts *css_token_stream) (css_color, error) {
		var res css_color
		res, ok := ts.parse_color()
		if !ok {
			return res, errors.New("illegal value")
		}
		return res, nil
	})
	if items == nil {
		return css_border_color_shorthand{}, false
	}
	res := css_border_color_shorthand{}
	switch len(items) {
	case 1:
		res.top = items[0]
		res.right = items[0]
		res.bottom = items[0]
		res.left = items[0]
	case 2:
		res.top = items[0]
		res.right = items[1]
		res.bottom = items[0]
		res.left = items[1]
	case 3:
		res.top = items[0]
		res.right = items[1]
		res.bottom = items[2]
		res.left = items[1]
	case 4:
		res.top = items[0]
		res.right = items[1]
		res.bottom = items[2]
		res.left = items[3]
	}
	return css_border_color_shorthand{}, false
}
func (sh css_border_color_shorthand) String() string {
	return fmt.Sprintf("%v %v %v %v", sh.top, sh.right, sh.bottom, sh.left)
}

type css_border_style_shorthand struct {
	top    css_line_style
	right  css_line_style
	bottom css_line_style
	left   css_line_style
}

func (ts *css_token_stream) parse_css_border_style_shorthand() (css_border_style_shorthand, bool) {
	items, _ := css_accept_repetion(ts, 4, func(ts *css_token_stream) (css_line_style, error) {
		var res css_line_style
		res, ok := ts.parse_line_style()
		if !ok {
			return res, errors.New("illegal value")
		}
		return res, nil
	})
	if items == nil {
		return css_border_style_shorthand{}, false
	}
	res := css_border_style_shorthand{}
	switch len(items) {
	case 1:
		res.top = items[0]
		res.right = items[0]
		res.bottom = items[0]
		res.left = items[0]
	case 2:
		res.top = items[0]
		res.right = items[1]
		res.bottom = items[0]
		res.left = items[1]
	case 3:
		res.top = items[0]
		res.right = items[1]
		res.bottom = items[2]
		res.left = items[1]
	case 4:
		res.top = items[0]
		res.right = items[1]
		res.bottom = items[2]
		res.left = items[3]
	}
	return css_border_style_shorthand{}, false
}
func (sh css_border_style_shorthand) String() string {
	return fmt.Sprintf("%v %v %v %v", sh.top, sh.right, sh.bottom, sh.left)
}

type css_border_width_shorthand struct {
	top    css_length
	right  css_length
	bottom css_length
	left   css_length
}

func (ts *css_token_stream) parse_css_border_width_shorthand() (css_border_width_shorthand, bool) {
	items, _ := css_accept_repetion(ts, 4, func(ts *css_token_stream) (css_length, error) {
		var res css_length
		res, ok := ts.parse_line_width()
		if !ok {
			return res, errors.New("illegal value")
		}
		return res, nil
	})
	if items == nil {
		return css_border_width_shorthand{}, false
	}
	res := css_border_width_shorthand{}
	switch len(items) {
	case 1:
		res.top = items[0]
		res.right = items[0]
		res.bottom = items[0]
		res.left = items[0]
	case 2:
		res.top = items[0]
		res.right = items[1]
		res.bottom = items[0]
		res.left = items[1]
	case 3:
		res.top = items[0]
		res.right = items[1]
		res.bottom = items[2]
		res.left = items[1]
	case 4:
		res.top = items[0]
		res.right = items[1]
		res.bottom = items[2]
		res.left = items[3]
	}
	return css_border_width_shorthand{}, false
}
func (sh css_border_width_shorthand) String() string {
	return fmt.Sprintf("%v %v %v %v", sh.top, sh.right, sh.bottom, sh.left)
}

type css_border_top_shorthand struct {
	border_top_width css_length
	border_top_style css_line_style
	border_top_color css_color
}

func (ts *css_token_stream) parse_css_border_top_shorthand() (css_border_top_shorthand, bool) {
	out := css_border_top_shorthand{css_line_width_medium(), css_line_style_none, css_color_currentColor()}
	got_border_top_width := false
	got_border_top_style := false
	got_border_top_color := false
	got_any := false
	for {
		valid := false
		if !got_border_top_width {
			ts.skip_whitespaces()
			if res, ok := ts.parse_line_width(); ok {
				out.border_top_width = res
				got_border_top_width = true
				valid = true
			}
		}
		if !got_border_top_style {
			ts.skip_whitespaces()
			if res, ok := ts.parse_line_style(); ok {
				out.border_top_style = res
				got_border_top_style = true
				valid = true
			}
		}
		if !got_border_top_color {
			ts.skip_whitespaces()
			if res, ok := ts.parse_color(); ok {
				out.border_top_color = res
				got_border_top_color = true
				valid = true
			}
		}
		ts.skip_whitespaces()
		if !valid {
			break
		}
		got_any = true
	}
	if !got_any {
		return out, false
	}
	return out, true
}

func (sh css_border_top_shorthand) String() string {
	return fmt.Sprintf("%v %v %v",
		sh.border_top_width,
		sh.border_top_style,
		sh.border_top_color,
	)
}

type css_border_right_shorthand struct {
	border_right_width css_length
	border_right_style css_line_style
	border_right_color css_color
}

func (ts *css_token_stream) parse_css_border_right_shorthand() (css_border_right_shorthand, bool) {
	out := css_border_right_shorthand{css_line_width_medium(), css_line_style_none, css_color_currentColor()}
	got_border_right_width := false
	got_border_right_style := false
	got_border_right_color := false
	got_any := false
	for {
		valid := false
		if !got_border_right_width {
			ts.skip_whitespaces()
			if res, ok := ts.parse_line_width(); ok {
				out.border_right_width = res
				got_border_right_width = true
				valid = true
			}
		}
		if !got_border_right_style {
			ts.skip_whitespaces()
			if res, ok := ts.parse_line_style(); ok {
				out.border_right_style = res
				got_border_right_style = true
				valid = true
			}
		}
		if !got_border_right_color {
			ts.skip_whitespaces()
			if res, ok := ts.parse_color(); ok {
				out.border_right_color = res
				got_border_right_color = true
				valid = true
			}
		}
		ts.skip_whitespaces()
		if !valid {
			break
		}
		got_any = true
	}
	if !got_any {
		return out, false
	}
	return out, true
}

func (sh css_border_right_shorthand) String() string {
	return fmt.Sprintf("%v %v %v",
		sh.border_right_width,
		sh.border_right_style,
		sh.border_right_color,
	)
}

type css_border_bottom_shorthand struct {
	border_bottom_width css_length
	border_bottom_style css_line_style
	border_bottom_color css_color
}

func (ts *css_token_stream) parse_css_border_bottom_shorthand() (css_border_bottom_shorthand, bool) {
	out := css_border_bottom_shorthand{css_line_width_medium(), css_line_style_none, css_color_currentColor()}
	got_border_bottom_width := false
	got_border_bottom_style := false
	got_border_bottom_color := false
	got_any := false
	for {
		valid := false
		if !got_border_bottom_width {
			ts.skip_whitespaces()
			if res, ok := ts.parse_line_width(); ok {
				out.border_bottom_width = res
				got_border_bottom_width = true
				valid = true
			}
		}
		if !got_border_bottom_style {
			ts.skip_whitespaces()
			if res, ok := ts.parse_line_style(); ok {
				out.border_bottom_style = res
				got_border_bottom_style = true
				valid = true
			}
		}
		if !got_border_bottom_color {
			ts.skip_whitespaces()
			if res, ok := ts.parse_color(); ok {
				out.border_bottom_color = res
				got_border_bottom_color = true
				valid = true
			}
		}
		ts.skip_whitespaces()
		if !valid {
			break
		}
		got_any = true
	}
	if !got_any {
		return out, false
	}
	return out, true
}

func (sh css_border_bottom_shorthand) String() string {
	return fmt.Sprintf("%v %v %v",
		sh.border_bottom_width,
		sh.border_bottom_style,
		sh.border_bottom_color,
	)
}

type css_border_left_shorthand struct {
	border_left_width css_length
	border_left_style css_line_style
	border_left_color css_color
}

func (ts *css_token_stream) parse_css_border_left_shorthand() (css_border_left_shorthand, bool) {
	out := css_border_left_shorthand{css_line_width_medium(), css_line_style_none, css_color_currentColor()}
	got_border_left_width := false
	got_border_left_style := false
	got_border_left_color := false
	got_any := false
	for {
		valid := false
		if !got_border_left_width {
			ts.skip_whitespaces()
			if res, ok := ts.parse_line_width(); ok {
				out.border_left_width = res
				got_border_left_width = true
				valid = true
			}
		}
		if !got_border_left_style {
			ts.skip_whitespaces()
			if res, ok := ts.parse_line_style(); ok {
				out.border_left_style = res
				got_border_left_style = true
				valid = true
			}
		}
		if !got_border_left_color {
			ts.skip_whitespaces()
			if res, ok := ts.parse_color(); ok {
				out.border_left_color = res
				got_border_left_color = true
				valid = true
			}
		}
		ts.skip_whitespaces()
		if !valid {
			break
		}
		got_any = true
	}
	if !got_any {
		return out, false
	}
	return out, true
}

func (sh css_border_left_shorthand) String() string {
	return fmt.Sprintf("%v %v %v",
		sh.border_left_width,
		sh.border_left_style,
		sh.border_left_color,
	)
}

type css_border_shorthand struct {
	border_width css_length
	border_style css_line_style
	border_color css_color
}

func (ts *css_token_stream) parse_css_border_shorthand() (css_border_shorthand, bool) {
	out := css_border_shorthand{css_line_width_medium(), css_line_style_none, css_color_currentColor()}
	got_border_width := false
	got_border_style := false
	got_border_color := false
	got_any := false
	for {
		valid := false
		if !got_border_width {
			ts.skip_whitespaces()
			if res, ok := ts.parse_line_width(); ok {
				out.border_width = res
				got_border_width = true
				valid = true
			}
		}
		if !got_border_style {
			ts.skip_whitespaces()
			if res, ok := ts.parse_line_style(); ok {
				out.border_style = res
				got_border_style = true
				valid = true
			}
		}
		if !got_border_color {
			ts.skip_whitespaces()
			if res, ok := ts.parse_color(); ok {
				out.border_color = res
				got_border_color = true
				valid = true
			}
		}
		ts.skip_whitespaces()
		if !valid {
			break
		}
		got_any = true
	}
	if !got_any {
		return out, false
	}
	return out, true
}

func (sh css_border_shorthand) String() string {
	return fmt.Sprintf("%v %v %v",
		sh.border_width,
		sh.border_style,
		sh.border_color,
	)
}

type css_margin_shorthand struct {
	top    css_margin
	right  css_margin
	bottom css_margin
	left   css_margin
}

func (ts *css_token_stream) parse_css_margin_shorthand() (css_margin_shorthand, bool) {
	items, _ := css_accept_repetion(ts, 4, func(ts *css_token_stream) (css_margin, error) {
		var res css_margin
		res, ok := ts.parse_margin()
		if !ok {
			return res, errors.New("illegal value")
		}
		return res, nil
	})
	if items == nil {
		return css_margin_shorthand{}, false
	}
	res := css_margin_shorthand{}
	switch len(items) {
	case 1:
		res.top = items[0]
		res.right = items[0]
		res.bottom = items[0]
		res.left = items[0]
	case 2:
		res.top = items[0]
		res.right = items[1]
		res.bottom = items[0]
		res.left = items[1]
	case 3:
		res.top = items[0]
		res.right = items[1]
		res.bottom = items[2]
		res.left = items[1]
	case 4:
		res.top = items[0]
		res.right = items[1]
		res.bottom = items[2]
		res.left = items[3]
	}
	return css_margin_shorthand{}, false
}
func (sh css_margin_shorthand) String() string {
	return fmt.Sprintf("%v %v %v %v", sh.top, sh.right, sh.bottom, sh.left)
}

type css_padding_shorthand struct {
	top    css_length_resolvable
	right  css_length_resolvable
	bottom css_length_resolvable
	left   css_length_resolvable
}

func (ts *css_token_stream) parse_css_padding_shorthand() (css_padding_shorthand, bool) {
	items, _ := css_accept_repetion(ts, 4, func(ts *css_token_stream) (css_length_resolvable, error) {
		var res css_length_resolvable
		res, ok := ts.parse_padding()
		if !ok {
			return res, errors.New("illegal value")
		}
		return res, nil
	})
	if items == nil {
		return css_padding_shorthand{}, false
	}
	res := css_padding_shorthand{}
	switch len(items) {
	case 1:
		res.top = items[0]
		res.right = items[0]
		res.bottom = items[0]
		res.left = items[0]
	case 2:
		res.top = items[0]
		res.right = items[1]
		res.bottom = items[0]
		res.left = items[1]
	case 3:
		res.top = items[0]
		res.right = items[1]
		res.bottom = items[2]
		res.left = items[1]
	case 4:
		res.top = items[0]
		res.right = items[1]
		res.bottom = items[2]
		res.left = items[3]
	}
	return css_padding_shorthand{}, false
}
func (sh css_padding_shorthand) String() string {
	return fmt.Sprintf("%v %v %v %v", sh.top, sh.right, sh.bottom, sh.left)
}

type css_font_shorthand struct {
	font_family  css_font_family_list
	font_weight  css_font_weight
	font_stretch css_font_stretch
	font_style   css_font_style
	font_size    css_font_size
}

func (ts *css_token_stream) parse_css_font_shorthand() (css_font_shorthand, bool) {
	out := css_font_shorthand{css_font_family_list{[]css_font_family{{css_font_family_type_sans_serif, ""}}}, css_font_weight_normal, css_font_stretch_normal, css_font_style_normal, css_absolute_size_medium}
	got_font_family := false
	got_font_weight := false
	got_font_stretch := false
	got_font_style := false
	got_font_size := false
	got_any := false
	for {
		valid := false
		if !got_font_family {
			ts.skip_whitespaces()
			if res, ok := ts.parse_font_family(); ok {
				out.font_family = res
				got_font_family = true
				valid = true
			}
		}
		if !got_font_weight {
			ts.skip_whitespaces()
			if res, ok := ts.parse_font_weight(); ok {
				out.font_weight = res
				got_font_weight = true
				valid = true
			}
		}
		if !got_font_stretch {
			ts.skip_whitespaces()
			if res, ok := ts.parse_font_stretch(); ok {
				out.font_stretch = res
				got_font_stretch = true
				valid = true
			}
		}
		if !got_font_style {
			ts.skip_whitespaces()
			if res, ok := ts.parse_font_style(); ok {
				out.font_style = res
				got_font_style = true
				valid = true
			}
		}
		if !got_font_size {
			ts.skip_whitespaces()
			if res, ok := ts.parse_font_size(); ok {
				out.font_size = res
				got_font_size = true
				valid = true
			}
		}
		ts.skip_whitespaces()
		if !valid {
			break
		}
		got_any = true
	}
	if !got_any {
		return out, false
	}
	return out, true
}

func (sh css_font_shorthand) String() string {
	return fmt.Sprintf("%v %v %v %v %v",
		sh.font_family,
		sh.font_weight,
		sh.font_stretch,
		sh.font_style,
		sh.font_size,
	)
}

var css_property_descriptors_map = map[string]css_property_descriptor{
	"color": {
		initial: css_color_CanvasText(),
		apply_func: func(dest *css_computed_style_set, value any) {
			v := value.(css_color)
			dest.color = &v
		},
		parse_func: func(ts *css_token_stream) (css_property_value, bool) {
			return ts.parse_color()
		},
	},
	"width": {
		initial: css_size_value_auto(),
		apply_func: func(dest *css_computed_style_set, value any) {
			v := value.(css_size_value)
			dest.width = &v
		},
		parse_func: func(ts *css_token_stream) (css_property_value, bool) {
			return ts.parse_size_value_or_auto()
		},
	},
	"height": {
		initial: css_size_value_auto(),
		apply_func: func(dest *css_computed_style_set, value any) {
			v := value.(css_size_value)
			dest.height = &v
		},
		parse_func: func(ts *css_token_stream) (css_property_value, bool) {
			return ts.parse_size_value_or_auto()
		},
	},
	"min-width": {
		initial: css_size_value_auto(),
		apply_func: func(dest *css_computed_style_set, value any) {
			v := value.(css_size_value)
			dest.min_width = &v
		},
		parse_func: func(ts *css_token_stream) (css_property_value, bool) {
			return ts.parse_size_value_or_auto()
		},
	},
	"min-height": {
		initial: css_size_value_auto(),
		apply_func: func(dest *css_computed_style_set, value any) {
			v := value.(css_size_value)
			dest.min_height = &v
		},
		parse_func: func(ts *css_token_stream) (css_property_value, bool) {
			return ts.parse_size_value_or_auto()
		},
	},
	"max-width": {
		initial: css_size_value_none(),
		apply_func: func(dest *css_computed_style_set, value any) {
			v := value.(css_size_value)
			dest.max_width = &v
		},
		parse_func: func(ts *css_token_stream) (css_property_value, bool) {
			return ts.parse_size_value_or_none()
		},
	},
	"max-height": {
		initial: css_size_value_none(),
		apply_func: func(dest *css_computed_style_set, value any) {
			v := value.(css_size_value)
			dest.max_height = &v
		},
		parse_func: func(ts *css_token_stream) (css_property_value, bool) {
			return ts.parse_size_value_or_none()
		},
	},
	"display": {
		initial: css_display{css_display_mode_outer_inner_mode, css_display_outer_mode_inline, css_display_inner_mode_flow},
		apply_func: func(dest *css_computed_style_set, value any) {
			v := value.(css_display)
			dest.display = &v
		},
		parse_func: func(ts *css_token_stream) (css_property_value, bool) {
			return ts.parse_display()
		},
	},
	"visibility": {
		initial: css_visibility_visible,
		apply_func: func(dest *css_computed_style_set, value any) {
			v := value.(css_visibility)
			dest.visibility = &v
		},
		parse_func: func(ts *css_token_stream) (css_property_value, bool) {
			return ts.parse_visibility()
		},
	},
	"background-color": {
		initial: css_color_transparent(),
		apply_func: func(dest *css_computed_style_set, value any) {
			v := value.(css_color)
			dest.background_color = &v
		},
		parse_func: func(ts *css_token_stream) (css_property_value, bool) {
			return ts.parse_color()
		},
	},
	"border-top-color": {
		initial: css_color_currentColor(),
		apply_func: func(dest *css_computed_style_set, value any) {
			v := value.(css_color)
			dest.border_top_color = &v
		},
		parse_func: func(ts *css_token_stream) (css_property_value, bool) {
			return ts.parse_color()
		},
	},
	"border-right-color": {
		initial: css_color_currentColor(),
		apply_func: func(dest *css_computed_style_set, value any) {
			v := value.(css_color)
			dest.border_right_color = &v
		},
		parse_func: func(ts *css_token_stream) (css_property_value, bool) {
			return ts.parse_color()
		},
	},
	"border-bottom-color": {
		initial: css_color_currentColor(),
		apply_func: func(dest *css_computed_style_set, value any) {
			v := value.(css_color)
			dest.border_bottom_color = &v
		},
		parse_func: func(ts *css_token_stream) (css_property_value, bool) {
			return ts.parse_color()
		},
	},
	"border-left-color": {
		initial: css_color_currentColor(),
		apply_func: func(dest *css_computed_style_set, value any) {
			v := value.(css_color)
			dest.border_left_color = &v
		},
		parse_func: func(ts *css_token_stream) (css_property_value, bool) {
			return ts.parse_color()
		},
	},
	"border-color": {
		initial: css_border_color_shorthand{css_color_currentColor(), css_color_currentColor(), css_color_currentColor(), css_color_currentColor()},
		apply_func: func(dest *css_computed_style_set, value any) {
			v := value.(css_border_color_shorthand)
			dest.border_color = &v
		},
		parse_func: func(ts *css_token_stream) (css_property_value, bool) {
			return ts.parse_css_border_color_shorthand()
		},
	},
	"border-top-style": {
		initial: css_line_style_none,
		apply_func: func(dest *css_computed_style_set, value any) {
			v := value.(css_line_style)
			dest.border_top_style = &v
		},
		parse_func: func(ts *css_token_stream) (css_property_value, bool) {
			return ts.parse_line_style()
		},
	},
	"border-right-style": {
		initial: css_line_style_none,
		apply_func: func(dest *css_computed_style_set, value any) {
			v := value.(css_line_style)
			dest.border_right_style = &v
		},
		parse_func: func(ts *css_token_stream) (css_property_value, bool) {
			return ts.parse_line_style()
		},
	},
	"border-bottom-style": {
		initial: css_line_style_none,
		apply_func: func(dest *css_computed_style_set, value any) {
			v := value.(css_line_style)
			dest.border_bottom_style = &v
		},
		parse_func: func(ts *css_token_stream) (css_property_value, bool) {
			return ts.parse_line_style()
		},
	},
	"border-left-style": {
		initial: css_line_style_none,
		apply_func: func(dest *css_computed_style_set, value any) {
			v := value.(css_line_style)
			dest.border_left_style = &v
		},
		parse_func: func(ts *css_token_stream) (css_property_value, bool) {
			return ts.parse_line_style()
		},
	},
	"border-style": {
		initial: css_border_style_shorthand{css_line_style_none, css_line_style_none, css_line_style_none, css_line_style_none},
		apply_func: func(dest *css_computed_style_set, value any) {
			v := value.(css_border_style_shorthand)
			dest.border_style = &v
		},
		parse_func: func(ts *css_token_stream) (css_property_value, bool) {
			return ts.parse_css_border_style_shorthand()
		},
	},
	"border-top-width": {
		initial: css_line_width_medium(),
		apply_func: func(dest *css_computed_style_set, value any) {
			v := value.(css_length)
			dest.border_top_width = &v
		},
		parse_func: func(ts *css_token_stream) (css_property_value, bool) {
			return ts.parse_line_width()
		},
	},
	"border-right-width": {
		initial: css_line_width_medium(),
		apply_func: func(dest *css_computed_style_set, value any) {
			v := value.(css_length)
			dest.border_right_width = &v
		},
		parse_func: func(ts *css_token_stream) (css_property_value, bool) {
			return ts.parse_line_width()
		},
	},
	"border-bottom-width": {
		initial: css_line_width_medium(),
		apply_func: func(dest *css_computed_style_set, value any) {
			v := value.(css_length)
			dest.border_bottom_width = &v
		},
		parse_func: func(ts *css_token_stream) (css_property_value, bool) {
			return ts.parse_line_width()
		},
	},
	"border-left-width": {
		initial: css_line_width_medium(),
		apply_func: func(dest *css_computed_style_set, value any) {
			v := value.(css_length)
			dest.border_left_width = &v
		},
		parse_func: func(ts *css_token_stream) (css_property_value, bool) {
			return ts.parse_line_width()
		},
	},
	"border-width": {
		initial: css_border_width_shorthand{css_line_width_medium(), css_line_width_medium(), css_line_width_medium(), css_line_width_medium()},
		apply_func: func(dest *css_computed_style_set, value any) {
			v := value.(css_border_width_shorthand)
			dest.border_width = &v
		},
		parse_func: func(ts *css_token_stream) (css_property_value, bool) {
			return ts.parse_css_border_width_shorthand()
		},
	},
	"border-top": {
		initial: css_border_top_shorthand{css_line_width_medium(), css_line_style_none, css_color_currentColor()},
		apply_func: func(dest *css_computed_style_set, value any) {
			v := value.(css_border_top_shorthand)
			dest.border_top = &v
		},
		parse_func: func(ts *css_token_stream) (css_property_value, bool) {
			return ts.parse_css_border_top_shorthand()
		},
	},
	"border-right": {
		initial: css_border_right_shorthand{css_line_width_medium(), css_line_style_none, css_color_currentColor()},
		apply_func: func(dest *css_computed_style_set, value any) {
			v := value.(css_border_right_shorthand)
			dest.border_right = &v
		},
		parse_func: func(ts *css_token_stream) (css_property_value, bool) {
			return ts.parse_css_border_right_shorthand()
		},
	},
	"border-bottom": {
		initial: css_border_bottom_shorthand{css_line_width_medium(), css_line_style_none, css_color_currentColor()},
		apply_func: func(dest *css_computed_style_set, value any) {
			v := value.(css_border_bottom_shorthand)
			dest.border_bottom = &v
		},
		parse_func: func(ts *css_token_stream) (css_property_value, bool) {
			return ts.parse_css_border_bottom_shorthand()
		},
	},
	"border-left": {
		initial: css_border_left_shorthand{css_line_width_medium(), css_line_style_none, css_color_currentColor()},
		apply_func: func(dest *css_computed_style_set, value any) {
			v := value.(css_border_left_shorthand)
			dest.border_left = &v
		},
		parse_func: func(ts *css_token_stream) (css_property_value, bool) {
			return ts.parse_css_border_left_shorthand()
		},
	},
	"border": {
		initial: css_border_shorthand{css_line_width_medium(), css_line_style_none, css_color_currentColor()},
		apply_func: func(dest *css_computed_style_set, value any) {
			v := value.(css_border_shorthand)
			dest.border = &v
		},
		parse_func: func(ts *css_token_stream) (css_property_value, bool) {
			return ts.parse_css_border_shorthand()
		},
	},
	"margin-top": {
		initial: css_margin{css_length{css_number_from_int(0), css_length_unit_px}},
		apply_func: func(dest *css_computed_style_set, value any) {
			v := value.(css_margin)
			dest.margin_top = &v
		},
		parse_func: func(ts *css_token_stream) (css_property_value, bool) {
			return ts.parse_margin()
		},
	},
	"margin-right": {
		initial: css_margin{css_length{css_number_from_int(0), css_length_unit_px}},
		apply_func: func(dest *css_computed_style_set, value any) {
			v := value.(css_margin)
			dest.margin_right = &v
		},
		parse_func: func(ts *css_token_stream) (css_property_value, bool) {
			return ts.parse_margin()
		},
	},
	"margin-bottom": {
		initial: css_margin{css_length{css_number_from_int(0), css_length_unit_px}},
		apply_func: func(dest *css_computed_style_set, value any) {
			v := value.(css_margin)
			dest.margin_bottom = &v
		},
		parse_func: func(ts *css_token_stream) (css_property_value, bool) {
			return ts.parse_margin()
		},
	},
	"margin-left": {
		initial: css_margin{css_length{css_number_from_int(0), css_length_unit_px}},
		apply_func: func(dest *css_computed_style_set, value any) {
			v := value.(css_margin)
			dest.margin_left = &v
		},
		parse_func: func(ts *css_token_stream) (css_property_value, bool) {
			return ts.parse_margin()
		},
	},
	"margin": {
		initial: css_margin_shorthand{css_margin{css_length{css_number_from_int(0), css_length_unit_px}}, css_margin{css_length{css_number_from_int(0), css_length_unit_px}}, css_margin{css_length{css_number_from_int(0), css_length_unit_px}}, css_margin{css_length{css_number_from_int(0), css_length_unit_px}}},
		apply_func: func(dest *css_computed_style_set, value any) {
			v := value.(css_margin_shorthand)
			dest.margin = &v
		},
		parse_func: func(ts *css_token_stream) (css_property_value, bool) {
			return ts.parse_css_margin_shorthand()
		},
	},
	"padding-top": {
		initial: css_length{css_number_from_int(0), css_length_unit_px},
		apply_func: func(dest *css_computed_style_set, value any) {
			v := value.(css_length_resolvable)
			dest.padding_top = &v
		},
		parse_func: func(ts *css_token_stream) (css_property_value, bool) {
			return ts.parse_padding()
		},
	},
	"padding-right": {
		initial: css_length{css_number_from_int(0), css_length_unit_px},
		apply_func: func(dest *css_computed_style_set, value any) {
			v := value.(css_length_resolvable)
			dest.padding_right = &v
		},
		parse_func: func(ts *css_token_stream) (css_property_value, bool) {
			return ts.parse_padding()
		},
	},
	"padding-bottom": {
		initial: css_length{css_number_from_int(0), css_length_unit_px},
		apply_func: func(dest *css_computed_style_set, value any) {
			v := value.(css_length_resolvable)
			dest.padding_bottom = &v
		},
		parse_func: func(ts *css_token_stream) (css_property_value, bool) {
			return ts.parse_padding()
		},
	},
	"padding-left": {
		initial: css_length{css_number_from_int(0), css_length_unit_px},
		apply_func: func(dest *css_computed_style_set, value any) {
			v := value.(css_length_resolvable)
			dest.padding_left = &v
		},
		parse_func: func(ts *css_token_stream) (css_property_value, bool) {
			return ts.parse_padding()
		},
	},
	"padding": {
		initial: css_padding_shorthand{css_length{css_number_from_int(0), css_length_unit_px}, css_length{css_number_from_int(0), css_length_unit_px}, css_length{css_number_from_int(0), css_length_unit_px}, css_length{css_number_from_int(0), css_length_unit_px}},
		apply_func: func(dest *css_computed_style_set, value any) {
			v := value.(css_padding_shorthand)
			dest.padding = &v
		},
		parse_func: func(ts *css_token_stream) (css_property_value, bool) {
			return ts.parse_css_padding_shorthand()
		},
	},
	"font-family ": {
		initial: css_font_family_list{[]css_font_family{{css_font_family_type_sans_serif, ""}}},
		apply_func: func(dest *css_computed_style_set, value any) {
			v := value.(css_font_family_list)
			dest.font_family = &v
		},
		parse_func: func(ts *css_token_stream) (css_property_value, bool) {
			return ts.parse_font_family()
		},
	},
	"font-weight": {
		initial: css_font_weight_normal,
		apply_func: func(dest *css_computed_style_set, value any) {
			v := value.(css_font_weight)
			dest.font_weight = &v
		},
		parse_func: func(ts *css_token_stream) (css_property_value, bool) {
			return ts.parse_font_weight()
		},
	},
	"font-stretch": {
		initial: css_font_stretch_normal,
		apply_func: func(dest *css_computed_style_set, value any) {
			v := value.(css_font_stretch)
			dest.font_stretch = &v
		},
		parse_func: func(ts *css_token_stream) (css_property_value, bool) {
			return ts.parse_font_stretch()
		},
	},
	"font-style": {
		initial: css_font_style_normal,
		apply_func: func(dest *css_computed_style_set, value any) {
			v := value.(css_font_style)
			dest.font_style = &v
		},
		parse_func: func(ts *css_token_stream) (css_property_value, bool) {
			return ts.parse_font_style()
		},
	},
	"font-size": {
		initial: css_absolute_size_medium,
		apply_func: func(dest *css_computed_style_set, value any) {
			v := value.(css_font_size)
			dest.font_size = &v
		},
		parse_func: func(ts *css_token_stream) (css_property_value, bool) {
			return ts.parse_font_size()
		},
	},
	"font": {
		initial: css_font_shorthand{css_font_family_list{[]css_font_family{{css_font_family_type_sans_serif, ""}}}, css_font_weight_normal, css_font_stretch_normal, css_font_style_normal, css_absolute_size_medium},
		apply_func: func(dest *css_computed_style_set, value any) {
			v := value.(css_font_shorthand)
			dest.font = &v
		},
		parse_func: func(ts *css_token_stream) (css_property_value, bool) {
			return ts.parse_css_font_shorthand()
		},
	},
}

type css_computed_style_set struct {
	color               *css_color
	width               *css_size_value
	height              *css_size_value
	min_width           *css_size_value
	min_height          *css_size_value
	max_width           *css_size_value
	max_height          *css_size_value
	display             *css_display
	visibility          *css_visibility
	background_color    *css_color
	border_top_color    *css_color
	border_right_color  *css_color
	border_bottom_color *css_color
	border_left_color   *css_color
	border_color        *css_border_color_shorthand
	border_top_style    *css_line_style
	border_right_style  *css_line_style
	border_bottom_style *css_line_style
	border_left_style   *css_line_style
	border_style        *css_border_style_shorthand
	border_top_width    *css_length
	border_right_width  *css_length
	border_bottom_width *css_length
	border_left_width   *css_length
	border_width        *css_border_width_shorthand
	border_top          *css_border_top_shorthand
	border_right        *css_border_right_shorthand
	border_bottom       *css_border_bottom_shorthand
	border_left         *css_border_left_shorthand
	border              *css_border_shorthand
	margin_top          *css_margin
	margin_right        *css_margin
	margin_bottom       *css_margin
	margin_left         *css_margin
	margin              *css_margin_shorthand
	padding_top         *css_length_resolvable
	padding_right       *css_length_resolvable
	padding_bottom      *css_length_resolvable
	padding_left        *css_length_resolvable
	padding             *css_padding_shorthand
	font_family         *css_font_family_list
	font_weight         *css_font_weight
	font_stretch        *css_font_stretch
	font_style          *css_font_style
	font_size           *css_font_size
	font                *css_font_shorthand
}

func (css *css_computed_style_set) get_color() css_color {
	if css.color == nil {
		initial := css_property_descriptors_map["color"].initial.(css_color)
		css.color = &initial
	}
	return *css.color
}
func (css *css_computed_style_set) get_width() css_size_value {
	if css.width == nil {
		initial := css_property_descriptors_map["width"].initial.(css_size_value)
		css.width = &initial
	}
	return *css.width
}
func (css *css_computed_style_set) get_height() css_size_value {
	if css.height == nil {
		initial := css_property_descriptors_map["height"].initial.(css_size_value)
		css.height = &initial
	}
	return *css.height
}
func (css *css_computed_style_set) get_min_width() css_size_value {
	if css.min_width == nil {
		initial := css_property_descriptors_map["min-width"].initial.(css_size_value)
		css.min_width = &initial
	}
	return *css.min_width
}
func (css *css_computed_style_set) get_min_height() css_size_value {
	if css.min_height == nil {
		initial := css_property_descriptors_map["min-height"].initial.(css_size_value)
		css.min_height = &initial
	}
	return *css.min_height
}
func (css *css_computed_style_set) get_max_width() css_size_value {
	if css.max_width == nil {
		initial := css_property_descriptors_map["max-width"].initial.(css_size_value)
		css.max_width = &initial
	}
	return *css.max_width
}
func (css *css_computed_style_set) get_max_height() css_size_value {
	if css.max_height == nil {
		initial := css_property_descriptors_map["max-height"].initial.(css_size_value)
		css.max_height = &initial
	}
	return *css.max_height
}
func (css *css_computed_style_set) get_display() css_display {
	if css.display == nil {
		initial := css_property_descriptors_map["display"].initial.(css_display)
		css.display = &initial
	}
	return *css.display
}
func (css *css_computed_style_set) get_visibility() css_visibility {
	if css.visibility == nil {
		initial := css_property_descriptors_map["visibility"].initial.(css_visibility)
		css.visibility = &initial
	}
	return *css.visibility
}
func (css *css_computed_style_set) get_background_color() css_color {
	if css.background_color == nil {
		initial := css_property_descriptors_map["background-color"].initial.(css_color)
		css.background_color = &initial
	}
	return *css.background_color
}
func (css *css_computed_style_set) get_border_top_color() css_color {
	if css.border_top_color == nil {
		initial := css_property_descriptors_map["border-top-color"].initial.(css_color)
		css.border_top_color = &initial
	}
	return *css.border_top_color
}
func (css *css_computed_style_set) get_border_right_color() css_color {
	if css.border_right_color == nil {
		initial := css_property_descriptors_map["border-right-color"].initial.(css_color)
		css.border_right_color = &initial
	}
	return *css.border_right_color
}
func (css *css_computed_style_set) get_border_bottom_color() css_color {
	if css.border_bottom_color == nil {
		initial := css_property_descriptors_map["border-bottom-color"].initial.(css_color)
		css.border_bottom_color = &initial
	}
	return *css.border_bottom_color
}
func (css *css_computed_style_set) get_border_left_color() css_color {
	if css.border_left_color == nil {
		initial := css_property_descriptors_map["border-left-color"].initial.(css_color)
		css.border_left_color = &initial
	}
	return *css.border_left_color
}
func (css *css_computed_style_set) get_border_color() css_border_color_shorthand {
	if css.border_color == nil {
		initial := css_property_descriptors_map["border-color"].initial.(css_border_color_shorthand)
		css.border_color = &initial
	}
	return *css.border_color
}
func (css *css_computed_style_set) get_border_top_style() css_line_style {
	if css.border_top_style == nil {
		initial := css_property_descriptors_map["border-top-style"].initial.(css_line_style)
		css.border_top_style = &initial
	}
	return *css.border_top_style
}
func (css *css_computed_style_set) get_border_right_style() css_line_style {
	if css.border_right_style == nil {
		initial := css_property_descriptors_map["border-right-style"].initial.(css_line_style)
		css.border_right_style = &initial
	}
	return *css.border_right_style
}
func (css *css_computed_style_set) get_border_bottom_style() css_line_style {
	if css.border_bottom_style == nil {
		initial := css_property_descriptors_map["border-bottom-style"].initial.(css_line_style)
		css.border_bottom_style = &initial
	}
	return *css.border_bottom_style
}
func (css *css_computed_style_set) get_border_left_style() css_line_style {
	if css.border_left_style == nil {
		initial := css_property_descriptors_map["border-left-style"].initial.(css_line_style)
		css.border_left_style = &initial
	}
	return *css.border_left_style
}
func (css *css_computed_style_set) get_border_style() css_border_style_shorthand {
	if css.border_style == nil {
		initial := css_property_descriptors_map["border-style"].initial.(css_border_style_shorthand)
		css.border_style = &initial
	}
	return *css.border_style
}
func (css *css_computed_style_set) get_border_top_width() css_length {
	if css.border_top_width == nil {
		initial := css_property_descriptors_map["border-top-width"].initial.(css_length)
		css.border_top_width = &initial
	}
	return *css.border_top_width
}
func (css *css_computed_style_set) get_border_right_width() css_length {
	if css.border_right_width == nil {
		initial := css_property_descriptors_map["border-right-width"].initial.(css_length)
		css.border_right_width = &initial
	}
	return *css.border_right_width
}
func (css *css_computed_style_set) get_border_bottom_width() css_length {
	if css.border_bottom_width == nil {
		initial := css_property_descriptors_map["border-bottom-width"].initial.(css_length)
		css.border_bottom_width = &initial
	}
	return *css.border_bottom_width
}
func (css *css_computed_style_set) get_border_left_width() css_length {
	if css.border_left_width == nil {
		initial := css_property_descriptors_map["border-left-width"].initial.(css_length)
		css.border_left_width = &initial
	}
	return *css.border_left_width
}
func (css *css_computed_style_set) get_border_width() css_border_width_shorthand {
	if css.border_width == nil {
		initial := css_property_descriptors_map["border-width"].initial.(css_border_width_shorthand)
		css.border_width = &initial
	}
	return *css.border_width
}
func (css *css_computed_style_set) get_border_top() css_border_top_shorthand {
	if css.border_top == nil {
		initial := css_property_descriptors_map["border-top"].initial.(css_border_top_shorthand)
		css.border_top = &initial
	}
	return *css.border_top
}
func (css *css_computed_style_set) get_border_right() css_border_right_shorthand {
	if css.border_right == nil {
		initial := css_property_descriptors_map["border-right"].initial.(css_border_right_shorthand)
		css.border_right = &initial
	}
	return *css.border_right
}
func (css *css_computed_style_set) get_border_bottom() css_border_bottom_shorthand {
	if css.border_bottom == nil {
		initial := css_property_descriptors_map["border-bottom"].initial.(css_border_bottom_shorthand)
		css.border_bottom = &initial
	}
	return *css.border_bottom
}
func (css *css_computed_style_set) get_border_left() css_border_left_shorthand {
	if css.border_left == nil {
		initial := css_property_descriptors_map["border-left"].initial.(css_border_left_shorthand)
		css.border_left = &initial
	}
	return *css.border_left
}
func (css *css_computed_style_set) get_border() css_border_shorthand {
	if css.border == nil {
		initial := css_property_descriptors_map["border"].initial.(css_border_shorthand)
		css.border = &initial
	}
	return *css.border
}
func (css *css_computed_style_set) get_margin_top() css_margin {
	if css.margin_top == nil {
		initial := css_property_descriptors_map["margin-top"].initial.(css_margin)
		css.margin_top = &initial
	}
	return *css.margin_top
}
func (css *css_computed_style_set) get_margin_right() css_margin {
	if css.margin_right == nil {
		initial := css_property_descriptors_map["margin-right"].initial.(css_margin)
		css.margin_right = &initial
	}
	return *css.margin_right
}
func (css *css_computed_style_set) get_margin_bottom() css_margin {
	if css.margin_bottom == nil {
		initial := css_property_descriptors_map["margin-bottom"].initial.(css_margin)
		css.margin_bottom = &initial
	}
	return *css.margin_bottom
}
func (css *css_computed_style_set) get_margin_left() css_margin {
	if css.margin_left == nil {
		initial := css_property_descriptors_map["margin-left"].initial.(css_margin)
		css.margin_left = &initial
	}
	return *css.margin_left
}
func (css *css_computed_style_set) get_margin() css_margin_shorthand {
	if css.margin == nil {
		initial := css_property_descriptors_map["margin"].initial.(css_margin_shorthand)
		css.margin = &initial
	}
	return *css.margin
}
func (css *css_computed_style_set) get_padding_top() css_length_resolvable {
	if css.padding_top == nil {
		initial := css_property_descriptors_map["padding-top"].initial.(css_length_resolvable)
		css.padding_top = &initial
	}
	return *css.padding_top
}
func (css *css_computed_style_set) get_padding_right() css_length_resolvable {
	if css.padding_right == nil {
		initial := css_property_descriptors_map["padding-right"].initial.(css_length_resolvable)
		css.padding_right = &initial
	}
	return *css.padding_right
}
func (css *css_computed_style_set) get_padding_bottom() css_length_resolvable {
	if css.padding_bottom == nil {
		initial := css_property_descriptors_map["padding-bottom"].initial.(css_length_resolvable)
		css.padding_bottom = &initial
	}
	return *css.padding_bottom
}
func (css *css_computed_style_set) get_padding_left() css_length_resolvable {
	if css.padding_left == nil {
		initial := css_property_descriptors_map["padding-left"].initial.(css_length_resolvable)
		css.padding_left = &initial
	}
	return *css.padding_left
}
func (css *css_computed_style_set) get_padding() css_padding_shorthand {
	if css.padding == nil {
		initial := css_property_descriptors_map["padding"].initial.(css_padding_shorthand)
		css.padding = &initial
	}
	return *css.padding
}
func (css *css_computed_style_set) get_font_family() css_font_family_list {
	if css.font_family == nil {
		initial := css_property_descriptors_map["font-family "].initial.(css_font_family_list)
		css.font_family = &initial
	}
	return *css.font_family
}
func (css *css_computed_style_set) get_font_weight() css_font_weight {
	if css.font_weight == nil {
		initial := css_property_descriptors_map["font-weight"].initial.(css_font_weight)
		css.font_weight = &initial
	}
	return *css.font_weight
}
func (css *css_computed_style_set) get_font_stretch() css_font_stretch {
	if css.font_stretch == nil {
		initial := css_property_descriptors_map["font-stretch"].initial.(css_font_stretch)
		css.font_stretch = &initial
	}
	return *css.font_stretch
}
func (css *css_computed_style_set) get_font_style() css_font_style {
	if css.font_style == nil {
		initial := css_property_descriptors_map["font-style"].initial.(css_font_style)
		css.font_style = &initial
	}
	return *css.font_style
}
func (css *css_computed_style_set) get_font_size() css_font_size {
	if css.font_size == nil {
		initial := css_property_descriptors_map["font-size"].initial.(css_font_size)
		css.font_size = &initial
	}
	return *css.font_size
}
func (css *css_computed_style_set) get_font() css_font_shorthand {
	if css.font == nil {
		initial := css_property_descriptors_map["font"].initial.(css_font_shorthand)
		css.font = &initial
	}
	return *css.font
}
