// Auto-generated by css/props/gen
// DO NOT EDIT.
package props

import (
	"fmt"

	"github.com/inseo-oh/yw/css"
	"github.com/inseo-oh/yw/css/backgrounds"
	"github.com/inseo-oh/yw/css/box"
	"github.com/inseo-oh/yw/css/csscolor"
	"github.com/inseo-oh/yw/css/display"
	"github.com/inseo-oh/yw/css/fonts"
	"github.com/inseo-oh/yw/css/sizing"
	"github.com/inseo-oh/yw/css/text"
	"github.com/inseo-oh/yw/css/values"
	"github.com/inseo-oh/yw/util"
)

type BorderColorShorthand struct {
	Top    csscolor.Color
	Right  csscolor.Color
	Bottom csscolor.Color
	Left   csscolor.Color
}

func (sh BorderColorShorthand) String() string {
	return fmt.Sprintf("%v %v %v %v", sh.Top, sh.Right, sh.Bottom, sh.Left)
}

type BorderStyleShorthand struct {
	Top    backgrounds.LineStyle
	Right  backgrounds.LineStyle
	Bottom backgrounds.LineStyle
	Left   backgrounds.LineStyle
}

func (sh BorderStyleShorthand) String() string {
	return fmt.Sprintf("%v %v %v %v", sh.Top, sh.Right, sh.Bottom, sh.Left)
}

type BorderWidthShorthand struct {
	Top    values.Length
	Right  values.Length
	Bottom values.Length
	Left   values.Length
}

func (sh BorderWidthShorthand) String() string {
	return fmt.Sprintf("%v %v %v %v", sh.Top, sh.Right, sh.Bottom, sh.Left)
}

type BorderTopShorthand struct {
	BorderTopWidth values.Length
	BorderTopStyle backgrounds.LineStyle
	BorderTopColor csscolor.Color
}

func (sh BorderTopShorthand) String() string {
	return fmt.Sprintf("%v %v %v",
		sh.BorderTopWidth,
		sh.BorderTopStyle,
		sh.BorderTopColor,
	)
}

type BorderRightShorthand struct {
	BorderRightWidth values.Length
	BorderRightStyle backgrounds.LineStyle
	BorderRightColor csscolor.Color
}

func (sh BorderRightShorthand) String() string {
	return fmt.Sprintf("%v %v %v",
		sh.BorderRightWidth,
		sh.BorderRightStyle,
		sh.BorderRightColor,
	)
}

type BorderBottomShorthand struct {
	BorderBottomWidth values.Length
	BorderBottomStyle backgrounds.LineStyle
	BorderBottomColor csscolor.Color
}

func (sh BorderBottomShorthand) String() string {
	return fmt.Sprintf("%v %v %v",
		sh.BorderBottomWidth,
		sh.BorderBottomStyle,
		sh.BorderBottomColor,
	)
}

type BorderLeftShorthand struct {
	BorderLeftWidth values.Length
	BorderLeftStyle backgrounds.LineStyle
	BorderLeftColor csscolor.Color
}

func (sh BorderLeftShorthand) String() string {
	return fmt.Sprintf("%v %v %v",
		sh.BorderLeftWidth,
		sh.BorderLeftStyle,
		sh.BorderLeftColor,
	)
}

type BorderShorthand struct {
	BorderWidthShorthand BorderWidthShorthand
	BorderStyleShorthand BorderStyleShorthand
	BorderColorShorthand BorderColorShorthand
}

func (sh BorderShorthand) String() string {
	return fmt.Sprintf("%v %v %v",
		sh.BorderWidthShorthand,
		sh.BorderStyleShorthand,
		sh.BorderColorShorthand,
	)
}

type MarginShorthand struct {
	Top    box.Margin
	Right  box.Margin
	Bottom box.Margin
	Left   box.Margin
}

func (sh MarginShorthand) String() string {
	return fmt.Sprintf("%v %v %v %v", sh.Top, sh.Right, sh.Bottom, sh.Left)
}

type PaddingShorthand struct {
	Top    values.LengthResolvable
	Right  values.LengthResolvable
	Bottom values.LengthResolvable
	Left   values.LengthResolvable
}

func (sh PaddingShorthand) String() string {
	return fmt.Sprintf("%v %v %v %v", sh.Top, sh.Right, sh.Bottom, sh.Left)
}

type FontShorthand struct {
	FontFamily  fonts.FamilyList
	FontWeight  fonts.Weight
	FontStretch fonts.Stretch
	FontStyle   fonts.Style
	FontSize    fonts.Size
}

func (sh FontShorthand) String() string {
	return fmt.Sprintf("%v %v %v %v %v",
		sh.FontFamily,
		sh.FontWeight,
		sh.FontStretch,
		sh.FontStyle,
		sh.FontSize,
	)
}

var DescriptorsMap = map[string]Descriptor{
	"color": {
		Initial: csscolor.CanvasText(),
		ApplyFunc: func(dest *ComputedStyleSet, value any) {
			v := value.(csscolor.Color)
			dest.ColorValue = &v
		},
	},
	"width": {
		Initial: sizing.Size{Type: sizing.Auto},
		ApplyFunc: func(dest *ComputedStyleSet, value any) {
			v := value.(sizing.Size)
			dest.WidthValue = &v
		},
	},
	"height": {
		Initial: sizing.Size{Type: sizing.Auto},
		ApplyFunc: func(dest *ComputedStyleSet, value any) {
			v := value.(sizing.Size)
			dest.HeightValue = &v
		},
	},
	"min-width": {
		Initial: sizing.Size{Type: sizing.Auto},
		ApplyFunc: func(dest *ComputedStyleSet, value any) {
			v := value.(sizing.Size)
			dest.MinWidthValue = &v
		},
	},
	"min-height": {
		Initial: sizing.Size{Type: sizing.Auto},
		ApplyFunc: func(dest *ComputedStyleSet, value any) {
			v := value.(sizing.Size)
			dest.MinHeightValue = &v
		},
	},
	"max-width": {
		Initial: sizing.Size{Type: sizing.NoneSize},
		ApplyFunc: func(dest *ComputedStyleSet, value any) {
			v := value.(sizing.Size)
			dest.MaxWidthValue = &v
		},
	},
	"max-height": {
		Initial: sizing.Size{Type: sizing.NoneSize},
		ApplyFunc: func(dest *ComputedStyleSet, value any) {
			v := value.(sizing.Size)
			dest.MaxHeightValue = &v
		},
	},
	"display": {
		Initial: display.Display{Mode: display.OuterInnerMode, OuterMode: display.Inline, InnerMode: display.Flow},
		ApplyFunc: func(dest *ComputedStyleSet, value any) {
			v := value.(display.Display)
			dest.DisplayValue = &v
		},
	},
	"visibility": {
		Initial: display.Visible,
		ApplyFunc: func(dest *ComputedStyleSet, value any) {
			v := value.(display.Visibility)
			dest.VisibilityValue = &v
		},
	},
	"background-color": {
		Initial: csscolor.Transparent(),
		ApplyFunc: func(dest *ComputedStyleSet, value any) {
			v := value.(csscolor.Color)
			dest.BackgroundColorValue = &v
		},
	},
	"border-top-color": {
		Initial: csscolor.NewCurrentColor(),
		ApplyFunc: func(dest *ComputedStyleSet, value any) {
			v := value.(csscolor.Color)
			dest.BorderTopColorValue = &v
		},
	},
	"border-right-color": {
		Initial: csscolor.NewCurrentColor(),
		ApplyFunc: func(dest *ComputedStyleSet, value any) {
			v := value.(csscolor.Color)
			dest.BorderRightColorValue = &v
		},
	},
	"border-bottom-color": {
		Initial: csscolor.NewCurrentColor(),
		ApplyFunc: func(dest *ComputedStyleSet, value any) {
			v := value.(csscolor.Color)
			dest.BorderBottomColorValue = &v
		},
	},
	"border-left-color": {
		Initial: csscolor.NewCurrentColor(),
		ApplyFunc: func(dest *ComputedStyleSet, value any) {
			v := value.(csscolor.Color)
			dest.BorderLeftColorValue = &v
		},
	},
	"border-color": {
		Initial: BorderColorShorthand{Left: csscolor.NewCurrentColor(), Top: csscolor.NewCurrentColor(), Right: csscolor.NewCurrentColor(), Bottom: csscolor.NewCurrentColor()},
		ApplyFunc: func(dest *ComputedStyleSet, value any) {
			v := value.(BorderColorShorthand)
			dest.BorderColorShorthandValue = &v
			dest.BorderTopColorValue = &v.Top
			dest.BorderRightColorValue = &v.Right
			dest.BorderBottomColorValue = &v.Bottom
			dest.BorderLeftColorValue = &v.Left
		},
	},
	"border-top-style": {
		Initial: backgrounds.NoLine,
		ApplyFunc: func(dest *ComputedStyleSet, value any) {
			v := value.(backgrounds.LineStyle)
			dest.BorderTopStyleValue = &v
		},
	},
	"border-right-style": {
		Initial: backgrounds.NoLine,
		ApplyFunc: func(dest *ComputedStyleSet, value any) {
			v := value.(backgrounds.LineStyle)
			dest.BorderRightStyleValue = &v
		},
	},
	"border-bottom-style": {
		Initial: backgrounds.NoLine,
		ApplyFunc: func(dest *ComputedStyleSet, value any) {
			v := value.(backgrounds.LineStyle)
			dest.BorderBottomStyleValue = &v
		},
	},
	"border-left-style": {
		Initial: backgrounds.NoLine,
		ApplyFunc: func(dest *ComputedStyleSet, value any) {
			v := value.(backgrounds.LineStyle)
			dest.BorderLeftStyleValue = &v
		},
	},
	"border-style": {
		Initial: BorderStyleShorthand{Left: backgrounds.NoLine, Top: backgrounds.NoLine, Right: backgrounds.NoLine, Bottom: backgrounds.NoLine},
		ApplyFunc: func(dest *ComputedStyleSet, value any) {
			v := value.(BorderStyleShorthand)
			dest.BorderStyleShorthandValue = &v
			dest.BorderTopStyleValue = &v.Top
			dest.BorderRightStyleValue = &v.Right
			dest.BorderBottomStyleValue = &v.Bottom
			dest.BorderLeftStyleValue = &v.Left
		},
	},
	"border-top-width": {
		Initial: backgrounds.LineWidthMedium(),
		ApplyFunc: func(dest *ComputedStyleSet, value any) {
			v := value.(values.Length)
			dest.BorderTopWidthValue = &v
		},
	},
	"border-right-width": {
		Initial: backgrounds.LineWidthMedium(),
		ApplyFunc: func(dest *ComputedStyleSet, value any) {
			v := value.(values.Length)
			dest.BorderRightWidthValue = &v
		},
	},
	"border-bottom-width": {
		Initial: backgrounds.LineWidthMedium(),
		ApplyFunc: func(dest *ComputedStyleSet, value any) {
			v := value.(values.Length)
			dest.BorderBottomWidthValue = &v
		},
	},
	"border-left-width": {
		Initial: backgrounds.LineWidthMedium(),
		ApplyFunc: func(dest *ComputedStyleSet, value any) {
			v := value.(values.Length)
			dest.BorderLeftWidthValue = &v
		},
	},
	"border-width": {
		Initial: BorderWidthShorthand{Left: backgrounds.LineWidthMedium(), Top: backgrounds.LineWidthMedium(), Right: backgrounds.LineWidthMedium(), Bottom: backgrounds.LineWidthMedium()},
		ApplyFunc: func(dest *ComputedStyleSet, value any) {
			v := value.(BorderWidthShorthand)
			dest.BorderWidthShorthandValue = &v
			dest.BorderTopWidthValue = &v.Top
			dest.BorderRightWidthValue = &v.Right
			dest.BorderBottomWidthValue = &v.Bottom
			dest.BorderLeftWidthValue = &v.Left
		},
	},
	"border-top": {
		Initial: BorderTopShorthand{BorderTopWidth: backgrounds.LineWidthMedium(), BorderTopStyle: backgrounds.NoLine, BorderTopColor: csscolor.NewCurrentColor()},
		ApplyFunc: func(dest *ComputedStyleSet, value any) {
			v := value.(BorderTopShorthand)
			dest.BorderTopShorthandValue = &v
			dest.BorderTopWidthValue = &v.BorderTopWidth
			dest.BorderTopStyleValue = &v.BorderTopStyle
			dest.BorderTopColorValue = &v.BorderTopColor
		},
	},
	"border-right": {
		Initial: BorderRightShorthand{BorderRightWidth: backgrounds.LineWidthMedium(), BorderRightStyle: backgrounds.NoLine, BorderRightColor: csscolor.NewCurrentColor()},
		ApplyFunc: func(dest *ComputedStyleSet, value any) {
			v := value.(BorderRightShorthand)
			dest.BorderRightShorthandValue = &v
			dest.BorderRightWidthValue = &v.BorderRightWidth
			dest.BorderRightStyleValue = &v.BorderRightStyle
			dest.BorderRightColorValue = &v.BorderRightColor
		},
	},
	"border-bottom": {
		Initial: BorderBottomShorthand{BorderBottomWidth: backgrounds.LineWidthMedium(), BorderBottomStyle: backgrounds.NoLine, BorderBottomColor: csscolor.NewCurrentColor()},
		ApplyFunc: func(dest *ComputedStyleSet, value any) {
			v := value.(BorderBottomShorthand)
			dest.BorderBottomShorthandValue = &v
			dest.BorderBottomWidthValue = &v.BorderBottomWidth
			dest.BorderBottomStyleValue = &v.BorderBottomStyle
			dest.BorderBottomColorValue = &v.BorderBottomColor
		},
	},
	"border-left": {
		Initial: BorderLeftShorthand{BorderLeftWidth: backgrounds.LineWidthMedium(), BorderLeftStyle: backgrounds.NoLine, BorderLeftColor: csscolor.NewCurrentColor()},
		ApplyFunc: func(dest *ComputedStyleSet, value any) {
			v := value.(BorderLeftShorthand)
			dest.BorderLeftShorthandValue = &v
			dest.BorderLeftWidthValue = &v.BorderLeftWidth
			dest.BorderLeftStyleValue = &v.BorderLeftStyle
			dest.BorderLeftColorValue = &v.BorderLeftColor
		},
	},
	"border": {
		Initial: BorderShorthand{BorderWidthShorthand: BorderWidthShorthand{Left: backgrounds.LineWidthMedium(), Top: backgrounds.LineWidthMedium(), Right: backgrounds.LineWidthMedium(), Bottom: backgrounds.LineWidthMedium()}, BorderStyleShorthand: BorderStyleShorthand{Left: backgrounds.NoLine, Top: backgrounds.NoLine, Right: backgrounds.NoLine, Bottom: backgrounds.NoLine}, BorderColorShorthand: BorderColorShorthand{Left: csscolor.NewCurrentColor(), Top: csscolor.NewCurrentColor(), Right: csscolor.NewCurrentColor(), Bottom: csscolor.NewCurrentColor()}},
		ApplyFunc: func(dest *ComputedStyleSet, value any) {
			v := value.(BorderShorthand)
			dest.BorderShorthandValue = &v
			dest.BorderWidthShorthandValue = &v.BorderWidthShorthand
			dest.BorderStyleShorthandValue = &v.BorderStyleShorthand
			dest.BorderColorShorthandValue = &v.BorderColorShorthand
		},
	},
	"margin-top": {
		Initial: box.Margin{Value: values.LengthFromPx(css.NumFromInt(0))},
		ApplyFunc: func(dest *ComputedStyleSet, value any) {
			v := value.(box.Margin)
			dest.MarginTopValue = &v
		},
	},
	"margin-right": {
		Initial: box.Margin{Value: values.LengthFromPx(css.NumFromInt(0))},
		ApplyFunc: func(dest *ComputedStyleSet, value any) {
			v := value.(box.Margin)
			dest.MarginRightValue = &v
		},
	},
	"margin-bottom": {
		Initial: box.Margin{Value: values.LengthFromPx(css.NumFromInt(0))},
		ApplyFunc: func(dest *ComputedStyleSet, value any) {
			v := value.(box.Margin)
			dest.MarginBottomValue = &v
		},
	},
	"margin-left": {
		Initial: box.Margin{Value: values.LengthFromPx(css.NumFromInt(0))},
		ApplyFunc: func(dest *ComputedStyleSet, value any) {
			v := value.(box.Margin)
			dest.MarginLeftValue = &v
		},
	},
	"margin": {
		Initial: MarginShorthand{Left: box.Margin{Value: values.LengthFromPx(css.NumFromInt(0))}, Top: box.Margin{Value: values.LengthFromPx(css.NumFromInt(0))}, Right: box.Margin{Value: values.LengthFromPx(css.NumFromInt(0))}, Bottom: box.Margin{Value: values.LengthFromPx(css.NumFromInt(0))}},
		ApplyFunc: func(dest *ComputedStyleSet, value any) {
			v := value.(MarginShorthand)
			dest.MarginShorthandValue = &v
			dest.MarginTopValue = &v.Top
			dest.MarginRightValue = &v.Right
			dest.MarginBottomValue = &v.Bottom
			dest.MarginLeftValue = &v.Left
		},
	},
	"padding-top": {
		Initial: values.LengthFromPx(css.NumFromInt(0)),
		ApplyFunc: func(dest *ComputedStyleSet, value any) {
			v := value.(values.LengthResolvable)
			dest.PaddingTopValue = &v
		},
	},
	"padding-right": {
		Initial: values.LengthFromPx(css.NumFromInt(0)),
		ApplyFunc: func(dest *ComputedStyleSet, value any) {
			v := value.(values.LengthResolvable)
			dest.PaddingRightValue = &v
		},
	},
	"padding-bottom": {
		Initial: values.LengthFromPx(css.NumFromInt(0)),
		ApplyFunc: func(dest *ComputedStyleSet, value any) {
			v := value.(values.LengthResolvable)
			dest.PaddingBottomValue = &v
		},
	},
	"padding-left": {
		Initial: values.LengthFromPx(css.NumFromInt(0)),
		ApplyFunc: func(dest *ComputedStyleSet, value any) {
			v := value.(values.LengthResolvable)
			dest.PaddingLeftValue = &v
		},
	},
	"padding": {
		Initial: PaddingShorthand{Left: values.LengthFromPx(css.NumFromInt(0)), Top: values.LengthFromPx(css.NumFromInt(0)), Right: values.LengthFromPx(css.NumFromInt(0)), Bottom: values.LengthFromPx(css.NumFromInt(0))},
		ApplyFunc: func(dest *ComputedStyleSet, value any) {
			v := value.(PaddingShorthand)
			dest.PaddingShorthandValue = &v
			dest.PaddingTopValue = &v.Top
			dest.PaddingRightValue = &v.Right
			dest.PaddingBottomValue = &v.Bottom
			dest.PaddingLeftValue = &v.Left
		},
	},
	"font-family": {
		Initial: fonts.FamilyList{Families: []fonts.Family{{Type: fonts.SansSerif}}},
		ApplyFunc: func(dest *ComputedStyleSet, value any) {
			v := value.(fonts.FamilyList)
			dest.FontFamilyValue = &v
		},
	},
	"font-weight": {
		Initial: fonts.NormalWeight,
		ApplyFunc: func(dest *ComputedStyleSet, value any) {
			v := value.(fonts.Weight)
			dest.FontWeightValue = &v
		},
	},
	"font-stretch": {
		Initial: fonts.NormalStretch,
		ApplyFunc: func(dest *ComputedStyleSet, value any) {
			v := value.(fonts.Stretch)
			dest.FontStretchValue = &v
		},
	},
	"font-style": {
		Initial: fonts.NormalStyle,
		ApplyFunc: func(dest *ComputedStyleSet, value any) {
			v := value.(fonts.Style)
			dest.FontStyleValue = &v
		},
	},
	"font-size": {
		Initial: fonts.MediumSize,
		ApplyFunc: func(dest *ComputedStyleSet, value any) {
			v := value.(fonts.Size)
			dest.FontSizeValue = &v
		},
	},
	"font": {
		Initial: FontShorthand{FontFamily: fonts.FamilyList{Families: []fonts.Family{{Type: fonts.SansSerif}}}, FontWeight: fonts.NormalWeight, FontStretch: fonts.NormalStretch, FontStyle: fonts.NormalStyle, FontSize: fonts.MediumSize},
		ApplyFunc: func(dest *ComputedStyleSet, value any) {
			v := value.(FontShorthand)
			dest.FontShorthandValue = &v
			dest.FontFamilyValue = &v.FontFamily
			dest.FontWeightValue = &v.FontWeight
			dest.FontStretchValue = &v.FontStretch
			dest.FontStyleValue = &v.FontStyle
			dest.FontSizeValue = &v.FontSize
		},
	},
	"text-transform": {
		Initial: text.Transform{Type: text.NoTransform},
		ApplyFunc: func(dest *ComputedStyleSet, value any) {
			v := value.(text.Transform)
			dest.TextTransformValue = &v
		},
	},
}

type ComputedStyleSet struct {
	ColorValue                 *csscolor.Color
	WidthValue                 *sizing.Size
	HeightValue                *sizing.Size
	MinWidthValue              *sizing.Size
	MinHeightValue             *sizing.Size
	MaxWidthValue              *sizing.Size
	MaxHeightValue             *sizing.Size
	DisplayValue               *display.Display
	VisibilityValue            *display.Visibility
	BackgroundColorValue       *csscolor.Color
	BorderTopColorValue        *csscolor.Color
	BorderRightColorValue      *csscolor.Color
	BorderBottomColorValue     *csscolor.Color
	BorderLeftColorValue       *csscolor.Color
	BorderColorShorthandValue  *BorderColorShorthand
	BorderTopStyleValue        *backgrounds.LineStyle
	BorderRightStyleValue      *backgrounds.LineStyle
	BorderBottomStyleValue     *backgrounds.LineStyle
	BorderLeftStyleValue       *backgrounds.LineStyle
	BorderStyleShorthandValue  *BorderStyleShorthand
	BorderTopWidthValue        *values.Length
	BorderRightWidthValue      *values.Length
	BorderBottomWidthValue     *values.Length
	BorderLeftWidthValue       *values.Length
	BorderWidthShorthandValue  *BorderWidthShorthand
	BorderTopShorthandValue    *BorderTopShorthand
	BorderRightShorthandValue  *BorderRightShorthand
	BorderBottomShorthandValue *BorderBottomShorthand
	BorderLeftShorthandValue   *BorderLeftShorthand
	BorderShorthandValue       *BorderShorthand
	MarginTopValue             *box.Margin
	MarginRightValue           *box.Margin
	MarginBottomValue          *box.Margin
	MarginLeftValue            *box.Margin
	MarginShorthandValue       *MarginShorthand
	PaddingTopValue            *values.LengthResolvable
	PaddingRightValue          *values.LengthResolvable
	PaddingBottomValue         *values.LengthResolvable
	PaddingLeftValue           *values.LengthResolvable
	PaddingShorthandValue      *PaddingShorthand
	FontFamilyValue            *fonts.FamilyList
	FontWeightValue            *fonts.Weight
	FontStretchValue           *fonts.Stretch
	FontStyleValue             *fonts.Style
	FontSizeValue              *fonts.Size
	FontShorthandValue         *FontShorthand
	TextTransformValue         *text.Transform
}

func (css *ComputedStyleSet) Color() csscolor.Color {
	if css.ColorValue == nil {
		initial := DescriptorsMap["color"].Initial.(csscolor.Color)
		css.ColorValue = &initial
	}
	return *css.ColorValue
}
func (css *ComputedStyleSet) inheritColorFromParent(parentSrc ComputedStyleSetSource) {
	parentCss := parentSrc.ComputedStyleSet()
	if !util.IsNil(parentCss.ColorValue) {
		css.ColorValue = parentCss.ColorValue
	} else if parentParentSrc := parentSrc.ParentSource(); !util.IsNil(parentParentSrc) {
		css.inheritColorFromParent(parentParentSrc)
	}
}
func (css *ComputedStyleSet) Width() sizing.Size {
	if css.WidthValue == nil {
		initial := DescriptorsMap["width"].Initial.(sizing.Size)
		css.WidthValue = &initial
	}
	return *css.WidthValue
}
func (css *ComputedStyleSet) Height() sizing.Size {
	if css.HeightValue == nil {
		initial := DescriptorsMap["height"].Initial.(sizing.Size)
		css.HeightValue = &initial
	}
	return *css.HeightValue
}
func (css *ComputedStyleSet) MinWidth() sizing.Size {
	if css.MinWidthValue == nil {
		initial := DescriptorsMap["min-width"].Initial.(sizing.Size)
		css.MinWidthValue = &initial
	}
	return *css.MinWidthValue
}
func (css *ComputedStyleSet) MinHeight() sizing.Size {
	if css.MinHeightValue == nil {
		initial := DescriptorsMap["min-height"].Initial.(sizing.Size)
		css.MinHeightValue = &initial
	}
	return *css.MinHeightValue
}
func (css *ComputedStyleSet) MaxWidth() sizing.Size {
	if css.MaxWidthValue == nil {
		initial := DescriptorsMap["max-width"].Initial.(sizing.Size)
		css.MaxWidthValue = &initial
	}
	return *css.MaxWidthValue
}
func (css *ComputedStyleSet) MaxHeight() sizing.Size {
	if css.MaxHeightValue == nil {
		initial := DescriptorsMap["max-height"].Initial.(sizing.Size)
		css.MaxHeightValue = &initial
	}
	return *css.MaxHeightValue
}
func (css *ComputedStyleSet) Display() display.Display {
	if css.DisplayValue == nil {
		initial := DescriptorsMap["display"].Initial.(display.Display)
		css.DisplayValue = &initial
	}
	return *css.DisplayValue
}
func (css *ComputedStyleSet) Visibility() display.Visibility {
	if css.VisibilityValue == nil {
		initial := DescriptorsMap["visibility"].Initial.(display.Visibility)
		css.VisibilityValue = &initial
	}
	return *css.VisibilityValue
}
func (css *ComputedStyleSet) inheritVisibilityFromParent(parentSrc ComputedStyleSetSource) {
	parentCss := parentSrc.ComputedStyleSet()
	if !util.IsNil(parentCss.VisibilityValue) {
		css.VisibilityValue = parentCss.VisibilityValue
	} else if parentParentSrc := parentSrc.ParentSource(); !util.IsNil(parentParentSrc) {
		css.inheritVisibilityFromParent(parentParentSrc)
	}
}
func (css *ComputedStyleSet) BackgroundColor() csscolor.Color {
	if css.BackgroundColorValue == nil {
		initial := DescriptorsMap["background-color"].Initial.(csscolor.Color)
		css.BackgroundColorValue = &initial
	}
	return *css.BackgroundColorValue
}
func (css *ComputedStyleSet) BorderTopColor() csscolor.Color {
	if css.BorderTopColorValue == nil {
		initial := DescriptorsMap["border-top-color"].Initial.(csscolor.Color)
		css.BorderTopColorValue = &initial
	}
	return *css.BorderTopColorValue
}
func (css *ComputedStyleSet) BorderRightColor() csscolor.Color {
	if css.BorderRightColorValue == nil {
		initial := DescriptorsMap["border-right-color"].Initial.(csscolor.Color)
		css.BorderRightColorValue = &initial
	}
	return *css.BorderRightColorValue
}
func (css *ComputedStyleSet) BorderBottomColor() csscolor.Color {
	if css.BorderBottomColorValue == nil {
		initial := DescriptorsMap["border-bottom-color"].Initial.(csscolor.Color)
		css.BorderBottomColorValue = &initial
	}
	return *css.BorderBottomColorValue
}
func (css *ComputedStyleSet) BorderLeftColor() csscolor.Color {
	if css.BorderLeftColorValue == nil {
		initial := DescriptorsMap["border-left-color"].Initial.(csscolor.Color)
		css.BorderLeftColorValue = &initial
	}
	return *css.BorderLeftColorValue
}
func (css *ComputedStyleSet) BorderTopStyle() backgrounds.LineStyle {
	if css.BorderTopStyleValue == nil {
		initial := DescriptorsMap["border-top-style"].Initial.(backgrounds.LineStyle)
		css.BorderTopStyleValue = &initial
	}
	return *css.BorderTopStyleValue
}
func (css *ComputedStyleSet) BorderRightStyle() backgrounds.LineStyle {
	if css.BorderRightStyleValue == nil {
		initial := DescriptorsMap["border-right-style"].Initial.(backgrounds.LineStyle)
		css.BorderRightStyleValue = &initial
	}
	return *css.BorderRightStyleValue
}
func (css *ComputedStyleSet) BorderBottomStyle() backgrounds.LineStyle {
	if css.BorderBottomStyleValue == nil {
		initial := DescriptorsMap["border-bottom-style"].Initial.(backgrounds.LineStyle)
		css.BorderBottomStyleValue = &initial
	}
	return *css.BorderBottomStyleValue
}
func (css *ComputedStyleSet) BorderLeftStyle() backgrounds.LineStyle {
	if css.BorderLeftStyleValue == nil {
		initial := DescriptorsMap["border-left-style"].Initial.(backgrounds.LineStyle)
		css.BorderLeftStyleValue = &initial
	}
	return *css.BorderLeftStyleValue
}
func (css *ComputedStyleSet) BorderTopWidth() values.Length {
	if css.BorderTopWidthValue == nil {
		initial := DescriptorsMap["border-top-width"].Initial.(values.Length)
		css.BorderTopWidthValue = &initial
	}
	return *css.BorderTopWidthValue
}
func (css *ComputedStyleSet) BorderRightWidth() values.Length {
	if css.BorderRightWidthValue == nil {
		initial := DescriptorsMap["border-right-width"].Initial.(values.Length)
		css.BorderRightWidthValue = &initial
	}
	return *css.BorderRightWidthValue
}
func (css *ComputedStyleSet) BorderBottomWidth() values.Length {
	if css.BorderBottomWidthValue == nil {
		initial := DescriptorsMap["border-bottom-width"].Initial.(values.Length)
		css.BorderBottomWidthValue = &initial
	}
	return *css.BorderBottomWidthValue
}
func (css *ComputedStyleSet) BorderLeftWidth() values.Length {
	if css.BorderLeftWidthValue == nil {
		initial := DescriptorsMap["border-left-width"].Initial.(values.Length)
		css.BorderLeftWidthValue = &initial
	}
	return *css.BorderLeftWidthValue
}
func (css *ComputedStyleSet) MarginTop() box.Margin {
	if css.MarginTopValue == nil {
		initial := DescriptorsMap["margin-top"].Initial.(box.Margin)
		css.MarginTopValue = &initial
	}
	return *css.MarginTopValue
}
func (css *ComputedStyleSet) MarginRight() box.Margin {
	if css.MarginRightValue == nil {
		initial := DescriptorsMap["margin-right"].Initial.(box.Margin)
		css.MarginRightValue = &initial
	}
	return *css.MarginRightValue
}
func (css *ComputedStyleSet) MarginBottom() box.Margin {
	if css.MarginBottomValue == nil {
		initial := DescriptorsMap["margin-bottom"].Initial.(box.Margin)
		css.MarginBottomValue = &initial
	}
	return *css.MarginBottomValue
}
func (css *ComputedStyleSet) MarginLeft() box.Margin {
	if css.MarginLeftValue == nil {
		initial := DescriptorsMap["margin-left"].Initial.(box.Margin)
		css.MarginLeftValue = &initial
	}
	return *css.MarginLeftValue
}
func (css *ComputedStyleSet) PaddingTop() values.LengthResolvable {
	if css.PaddingTopValue == nil {
		initial := DescriptorsMap["padding-top"].Initial.(values.LengthResolvable)
		css.PaddingTopValue = &initial
	}
	return *css.PaddingTopValue
}
func (css *ComputedStyleSet) PaddingRight() values.LengthResolvable {
	if css.PaddingRightValue == nil {
		initial := DescriptorsMap["padding-right"].Initial.(values.LengthResolvable)
		css.PaddingRightValue = &initial
	}
	return *css.PaddingRightValue
}
func (css *ComputedStyleSet) PaddingBottom() values.LengthResolvable {
	if css.PaddingBottomValue == nil {
		initial := DescriptorsMap["padding-bottom"].Initial.(values.LengthResolvable)
		css.PaddingBottomValue = &initial
	}
	return *css.PaddingBottomValue
}
func (css *ComputedStyleSet) PaddingLeft() values.LengthResolvable {
	if css.PaddingLeftValue == nil {
		initial := DescriptorsMap["padding-left"].Initial.(values.LengthResolvable)
		css.PaddingLeftValue = &initial
	}
	return *css.PaddingLeftValue
}
func (css *ComputedStyleSet) FontFamily() fonts.FamilyList {
	if css.FontFamilyValue == nil {
		initial := DescriptorsMap["font-family"].Initial.(fonts.FamilyList)
		css.FontFamilyValue = &initial
	}
	return *css.FontFamilyValue
}
func (css *ComputedStyleSet) inheritFontFamilyFromParent(parentSrc ComputedStyleSetSource) {
	parentCss := parentSrc.ComputedStyleSet()
	if !util.IsNil(parentCss.FontFamilyValue) {
		css.FontFamilyValue = parentCss.FontFamilyValue
	} else if parentParentSrc := parentSrc.ParentSource(); !util.IsNil(parentParentSrc) {
		css.inheritFontFamilyFromParent(parentParentSrc)
	}
}
func (css *ComputedStyleSet) FontWeight() fonts.Weight {
	if css.FontWeightValue == nil {
		initial := DescriptorsMap["font-weight"].Initial.(fonts.Weight)
		css.FontWeightValue = &initial
	}
	return *css.FontWeightValue
}
func (css *ComputedStyleSet) inheritFontWeightFromParent(parentSrc ComputedStyleSetSource) {
	parentCss := parentSrc.ComputedStyleSet()
	if !util.IsNil(parentCss.FontWeightValue) {
		css.FontWeightValue = parentCss.FontWeightValue
	} else if parentParentSrc := parentSrc.ParentSource(); !util.IsNil(parentParentSrc) {
		css.inheritFontWeightFromParent(parentParentSrc)
	}
}
func (css *ComputedStyleSet) FontStretch() fonts.Stretch {
	if css.FontStretchValue == nil {
		initial := DescriptorsMap["font-stretch"].Initial.(fonts.Stretch)
		css.FontStretchValue = &initial
	}
	return *css.FontStretchValue
}
func (css *ComputedStyleSet) inheritFontStretchFromParent(parentSrc ComputedStyleSetSource) {
	parentCss := parentSrc.ComputedStyleSet()
	if !util.IsNil(parentCss.FontStretchValue) {
		css.FontStretchValue = parentCss.FontStretchValue
	} else if parentParentSrc := parentSrc.ParentSource(); !util.IsNil(parentParentSrc) {
		css.inheritFontStretchFromParent(parentParentSrc)
	}
}
func (css *ComputedStyleSet) FontStyle() fonts.Style {
	if css.FontStyleValue == nil {
		initial := DescriptorsMap["font-style"].Initial.(fonts.Style)
		css.FontStyleValue = &initial
	}
	return *css.FontStyleValue
}
func (css *ComputedStyleSet) inheritFontStyleFromParent(parentSrc ComputedStyleSetSource) {
	parentCss := parentSrc.ComputedStyleSet()
	if !util.IsNil(parentCss.FontStyleValue) {
		css.FontStyleValue = parentCss.FontStyleValue
	} else if parentParentSrc := parentSrc.ParentSource(); !util.IsNil(parentParentSrc) {
		css.inheritFontStyleFromParent(parentParentSrc)
	}
}
func (css *ComputedStyleSet) FontSize() fonts.Size {
	if css.FontSizeValue == nil {
		initial := DescriptorsMap["font-size"].Initial.(fonts.Size)
		css.FontSizeValue = &initial
	}
	return *css.FontSizeValue
}
func (css *ComputedStyleSet) inheritFontSizeFromParent(parentSrc ComputedStyleSetSource) {
	parentCss := parentSrc.ComputedStyleSet()
	if !util.IsNil(parentCss.FontSizeValue) {
		css.FontSizeValue = parentCss.FontSizeValue
	} else if parentParentSrc := parentSrc.ParentSource(); !util.IsNil(parentParentSrc) {
		css.inheritFontSizeFromParent(parentParentSrc)
	}
}
func (css *ComputedStyleSet) inheritFontShorthandFromParent(parentSrc ComputedStyleSetSource) {
	parentCss := parentSrc.ComputedStyleSet()
	if !util.IsNil(parentCss.FontShorthandValue) {
		css.FontFamilyValue = &parentCss.FontShorthandValue.FontFamily
		css.FontWeightValue = &parentCss.FontShorthandValue.FontWeight
		css.FontStretchValue = &parentCss.FontShorthandValue.FontStretch
		css.FontStyleValue = &parentCss.FontShorthandValue.FontStyle
		css.FontSizeValue = &parentCss.FontShorthandValue.FontSize
		css.FontShorthandValue = parentCss.FontShorthandValue
	} else if parentParentSrc := parentSrc.ParentSource(); !util.IsNil(parentParentSrc) {
		css.inheritFontShorthandFromParent(parentParentSrc)
	}
}
func (css *ComputedStyleSet) TextTransform() text.Transform {
	if css.TextTransformValue == nil {
		initial := DescriptorsMap["text-transform"].Initial.(text.Transform)
		css.TextTransformValue = &initial
	}
	return *css.TextTransformValue
}
func (css *ComputedStyleSet) inheritTextTransformFromParent(parentSrc ComputedStyleSetSource) {
	parentCss := parentSrc.ComputedStyleSet()
	if !util.IsNil(parentCss.TextTransformValue) {
		css.TextTransformValue = parentCss.TextTransformValue
	} else if parentParentSrc := parentSrc.ParentSource(); !util.IsNil(parentParentSrc) {
		css.inheritTextTransformFromParent(parentParentSrc)
	}
}
func (css *ComputedStyleSet) InheritPropertiesFromParent(parentSrc ComputedStyleSetSource) {
	if util.IsNil(css.ColorValue) {
		css.inheritColorFromParent(parentSrc)
	}
	if util.IsNil(css.VisibilityValue) {
		css.inheritVisibilityFromParent(parentSrc)
	}
	if util.IsNil(css.FontFamilyValue) {
		css.inheritFontFamilyFromParent(parentSrc)
	}
	if util.IsNil(css.FontWeightValue) {
		css.inheritFontWeightFromParent(parentSrc)
	}
	if util.IsNil(css.FontStretchValue) {
		css.inheritFontStretchFromParent(parentSrc)
	}
	if util.IsNil(css.FontStyleValue) {
		css.inheritFontStyleFromParent(parentSrc)
	}
	if util.IsNil(css.FontSizeValue) {
		css.inheritFontSizeFromParent(parentSrc)
	}
	if util.IsNil(css.FontShorthandValue) {
		css.inheritFontShorthandFromParent(parentSrc)
	}
	if util.IsNil(css.TextTransformValue) {
		css.inheritTextTransformFromParent(parentSrc)
	}
}
